export const db = [
  {
    id: "1",
    title: "Grêmio",
    slug: "gremio",
    titleAmount: "5",
    shieldFormat: "circle",
    shieldColor: ["white", "black", "blue"],
    zone: "Sul",
    city: "Porto Alegre",
    state: "RS",
    mascot: "Mosqueteiro",
    mascotType: "Human",
    lastTitleYear: "2016",
    rankingPosition: "2",
    url: "https://seeklogo.com/images/G/gremio-logo-DA302F6D10-seeklogo.com.png",
  },
  {
    id: "2",
    title: "Flamengo",
    slug: "flamengo",
    titleAmount: "4",
    shieldFormat: "square",
    shieldColor: ["red", "black"],
    zone: "Sudeste",
    city: "Rio de Janeiro",
    state: "RJ",
    mascot: "Urubu",
    mascotType: "Animal",
    lastTitleYear: "2022",
    rankingPosition: "4",
    url: "https://www.logotypes101.com/logos/484/E140F97473EFBC49D4B63B1528D97E57/Flamengo.png",
  },
  {
    id: "3",
    title: "Atlético MG",
    slug: "atletico",
    titleAmount: "2",
    shieldFormat: "square",
    shieldColor: ["white", "black"],
    zone: "Sudeste",
    city: "Belo Horizonte",
    state: "MG",
    mascot: "Galo",
    mascotType: "Animal",
    lastTitleYear: "2021",
    rankingPosition: "6",
    url: "https://logodetimes.com/times/atletico-mineiro/logo-atletico-mineiro-4096.png",
  },
  {
    id: "4",
    title: "Corinthians",
    slug: "corinthians",
    titleAmount: "2",
    shieldFormat: "square",
    shieldColor: ["white", "black"],
    zone: "Sudeste",
    city: "São Paulo",
    state: "SP",
    mascot: "Mosqueteiro",
    mascotType: "Human",
    lastTitleYear: "2009",
    rankingPosition: "5",
    url: "https://logodetimes.com/wp-content/uploads/corinthians.png",
  },
  {
    id: "5",
    title: "Cruzeiro",
    slug: "cruzeiro",
    titleAmount: "6",
    shieldFormat: "circle",
    shieldColor: ["white", "blue"],
    zone: "Sudeste",
    city: "Belo Horizonte",
    state: "MG",
    mascot: "Raposa",
    mascotType: "Animal",
    lastTitleYear: "2018",
    rankingPosition: "1",
    url: "https://seeklogo.com/images/C/cruzeiro-esporte-clube-logo-D1A04C7699-seeklogo.com.png",
  },
  {
    id: "6",
    title: "Palmeiras",
    slug: "palmeiras",
    titleAmount: "4",
    shieldFormat: "circle",
    shieldColor: ["white", "green"],
    zone: "Sudeste",
    city: "São Paulo",
    state: "SP",
    mascot: "Porco",
    mascotType: "Animal",
    lastTitleYear: "2020",
    rankingPosition: "3",
    url: "https://logodetimes.com/times/palmeiras/logo-palmeiras-2048.png",
  },
];
